api_version = "2026-04"
[[extensions]]
name = "t:name"
description = "t:description"
handle = "bundle-aware-bxgy-settings"
uid = "11d7c1df-2f8a-4228-9c98-8abab00ce64b"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"

[[extensions.metafields]]
namespace = "$app"
key = "function-configuration"
