api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "bulk-edit-metafields"
type = "ui_extension"
uid = "7df08bc4-5602-afc2-bd59-822753280309f6d0a7a6"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-details.action.render"

[[extensions]]
name = "t:name"
handle = "bulk-edit-metafields-index"
type = "ui_extension"
uid = "7c1744a3-48eb-4012-a1b1-dd0588f089ca"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-index.selection-action.render"

[[extensions]]
name = "t:name"
handle = "bulk-edit-metafields-index-action"
type = "ui_extension"
uid = "1776742b-a8b1-48df-bc3d-e1ff69a1bc17"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-index.action.render"
