api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "pvx-sync"
type = "ui_extension"
uid = "608e17bd-8899-1a0c-9146-c43b2dcda0acb09635d5"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-details.action.render"

[[extensions]]
name = "t:name"
handle = "pvx-sync-bulk"
type = "ui_extension"
uid = "4da9a59c-5450-4961-b5a7-17f98515203f"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-index.selection-action.render"

[[extensions]]
name = "t:name"
handle = "pvx-status-block"
uid = "5920e4b9-b390-268d-c2a8-9b35786c41630ae13871"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/ProductStatusBlock.jsx"
target = "admin.product-details.block.render"

[[extensions]]
name = "t:inventory-sync-action-name"
handle = "pvx-sync-inventory"
uid = "53a12559-e746-b0b6-0a05-0c014afc4cc66386e1d2"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/InventorySyncAction.jsx"
target = "admin.product-details.action.render"

[[extensions]]
name = "t:inventory-sync-action-name"
handle = "pvx-sync-inventory-index"
uid = "8f082bee-046d-7ad0-b440-edbc6f277e372e577b21"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/InventorySyncAction.jsx"
target = "admin.product-index.selection-action.render"
