api_version = "2026-04"
uid = "a790f479-2fc3-ac0c-ddee-72de0801731bdfcb6115"

[[extensions]]
name = "t:name"
handle = "wishlist-stale-checker"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/WishlistStalenessCheck.jsx"
target = "admin.customer-details.action.render"
